# Generated by Django 2.2.4 on 2019-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofficer',
            name='farmers',
        ),
        migrations.AddField(
            model_name='fieldofficer',
            name='farmers',
            field=models.ManyToManyField(blank=True, to='hsapp.Farmer'),
        ),
    ]
