# Generated by Django 2.2.4 on 2019-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0003_auto_20190922_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='birth_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state_id_picture',
            field=models.FilePathField(blank=True),
        ),
    ]
