# Generated by Django 2.2.4 on 2019-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0005_auto_20190923_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='state_id_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
