# Generated by Django 2.2.4 on 2019-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0006_auto_20190923_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='land_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='leased_land',
            field=models.BooleanField(default=False),
        ),
    ]
