# Generated by Django 2.2.4 on 2019-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0007_auto_20190923_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='state_id_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
