# Generated by Django 2.2.4 on 2019-09-24 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0008_auto_20190923_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_or_appointment', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.TimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer')),
            ],
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='dealer_id',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='dealerfarmerrelation',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='dealerfarmerrelation',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='dealerproducts',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='dealerproducts',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='escalation',
            name='fo_id',
        ),
        migrations.RemoveField(
            model_name='farmerinterests',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='farmerinterests',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='farmerinterests',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='farmerplant',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='farmerplant',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='fieldofficer',
            name='farmer_ids',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='season',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='prospectfarmer',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product_id',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerfarmerrelation',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerfarmerrelation',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerproducts',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealerproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalation',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalation',
            name='field_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.FieldOfficer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerinterests',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerinterests',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerplant',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerplant',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldofficer',
            name='farmers',
            field=models.ManyToManyField(to='hsapp.Farmer'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospectfarmer',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='farmer',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealerfarmerrelation',
            name='close_relation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealerproducts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmerinterests',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='visitfarmer',
            name='filed_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsapp.FieldOfficer'),
        ),
    ]
