# Generated by Django 2.2.4 on 2019-09-24 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0009_auto_20190924_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitfarmer',
            name='filed_officer',
        ),
        migrations.AddField(
            model_name='visitfarmer',
            name='field_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.FieldOfficer'),
        ),
        migrations.AlterField(
            model_name='dealerfarmerrelation',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
        ),
        migrations.AlterField(
            model_name='dealerfarmerrelation',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='dealerproducts',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
        ),
        migrations.AlterField(
            model_name='dealerproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Product'),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='field_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.FieldOfficer'),
        ),
        migrations.AlterField(
            model_name='farmerinterests',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='farmerinterests',
            name='interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmerinterests',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
        ),
        migrations.AlterField(
            model_name='farmerplant',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='farmerplant',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
        ),
        migrations.AlterField(
            model_name='farmerplant',
            name='plant_period',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fieldofficer',
            name='farmers',
            field=models.ManyToManyField(blank=True, default=[1], to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prospectfarmer',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Plant'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitfarmer',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Farmer'),
        ),
        migrations.CreateModel(
            name='VisitDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_or_appointment', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.TimeField(default=django.utils.timezone.now)),
                ('dealer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Dealer')),
                ('field_officer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsapp.FieldOfficer')),
            ],
        ),
    ]
