# Generated by Django 2.2.4 on 2019-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0010_auto_20190924_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealerProducts',
            new_name='DealerProduct',
        ),
        migrations.RenameModel(
            old_name='FarmerInterests',
            new_name='FarmerInterest',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
