# Generated by Django 2.2.4 on 2019-08-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='vote',
        ),
    ]
