# Generated by Django 2.2.4 on 2019-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Nobody', max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('reserve', models.IntegerField(default=20)),
            ],
        ),
    ]
