# Generated by Django 2.2.4 on 2019-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nobody', max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('reserve', models.IntegerField(default=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Bath',
        ),
    ]
