# Generated by Django 2.2.4 on 2019-08-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0002_auto_20190828_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reserve',
            new_name='reserve_time',
        ),
    ]
