# Generated by Django 2.2.4 on 2019-08-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bath', '0003_auto_20190828_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
